name: Feishu Notify
on: [push]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - run: >
              curl -X POST -H 'Content-Type: application/json' -d '{"msg_type":"text","content":{"text":"Github已更新"}}' ${{ secrets.FEISHU_PUSH_URL }}
