name: Feishu Notify
on: [push]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: jitterbit/get-changed-files@v1
        id: changed_files
        with:
          format: space-delimited
      - run: >
              curl -X POST -H 'Content-Type: application/json' \
              -d '{"msg_type":"text","content": \
              {"text":"Github已更新\\n更新内容：${{ steps.changed_files.outputs.added_modified }}"}}' \
              ${{ secrets.FEISHU_PUSH_URL }}
